stages:
  - module-pipelines

frontend:
  stage: module-pipelines
  trigger:
    include:
      - "/frontend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipelines
  trigger:
    include:
      - "/backend/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - backend/**/*

helm-momo-store-chart:
  stage: module-pipelines
  trigger:
    include:
      - "/helm/.gitlab-ci.yml"
    strategy: depend
  only:
    changes:
      - helm/momo-store-chart/**/*
      - helm/.gitlab-ci.yml
